# Generated by Django 4.0.2 on 2022-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparatservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='followers',
            field=models.IntegerField(),
        ),
    ]
