# Generated by Django 4.0.2 on 2022-02-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparatservice', '0002_alter_interface_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('date_expire', models.DateField()),
                ('who_publish', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='interface',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
